version: '3.8'

x-app-service: &default-app
  build: .
  command: ''
  volumes:
    - .:/code:delegated
    - node_modules:/code/node_modules:delegated

services:

  backoffice-backend:
    <<: *default-app
    command: bash -c "npm run build && npm run start:backoffice:backend"
    ports:
      - 3000:3000

volumes:
  node_modules: