services:

  Apps.Backoffice.Backend.controllers.StatusGetController:
    class: ../../controllers/StatusGetController
    arguments: []

  Apps.Backoffice.Backend.controllers.RehersalsPutController:
    class: ../../controllers/RehersalsPutController
    arguments: ["@Backoffice.Rehersals.application.RehersalCreator"]